//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LANoiproui.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_LANOIPROUI_DIALOG           102
#define IDS_VALID_EMAIL_ADDRESS         102
#define IDS_SESSIONPAGE_SUBTITLE        103
#define IDS_INVITE_FILE_EXTENSION_FILTER 104
#define IDS_ERR_EMPTY_NICKNAME          105
#define IDS_OPEN_INVITE_DLG_CAPTION     106
#define IDS_LOG_TRACE_REG_KEY           107
#define IDS_TRACE_FILENAME              108
#define IDS_CREATE_INVITATION_SUCCESS   109
#define IDS_JOIN_INVITATION_SUCCESS     110
#define IDS_JOIN_INVITATION_FAILURE     111
#define IDS_ERR_INVALID_SESSIONNAME     112
#define IDS_ERR_FAILED_TO_SAVE_INVITATION 113
#define IDS_ERR_SERVICE_NOT_STARTED     114
#define IDS_ERR_EMPTY_SESSION_NAME      115
#define IDS_ERR_EMPTY_PORT_VALUES       116
#define IDS_SESSION_NAME_EXISTS         117
#define IDS_EXE_FILE_EXTENSION_FILTER   118
#define IDS_OPEN_EXE_DLG_CAPTION        119
#define IDS_EXE_FILE_EXTENSION          120
#define IDS_ADVANCED_BTN_EXPAND         121
#define IDS_ADVANCED_BTN_CONTRACT       122
#define IDS_JOINER_CONNECTING_INVITER   123
#define IDS_APP_TITLE                   124
#define IDS_BALLON_P2P_STARTED          125
#define IDS_TOOLTIP_P2P_STARTED         126
#define IDS_BALLONTIP_P2P_FAILED        127
#define IDS_TOOLTIP_P2P_FAILED          128
#define IDR_UI_MENU                     129
#define IDS_ADD_NETWORK_WIZARD_CAPTION  129
#define IDS_JOINER_RESOLVING_INVITER    130
#define IDD_SESSION_SELECT              131
#define IDS_JOIN_NETWORK_WIZARD_CAPTION 131
#define IDD_INVITATION_SAVE             132
#define IDS_EXISTING_NETWORK_WIZARD_CAPTION 132
#define IDD_INVITATION_AUTH             133
#define IDS_NO_VALID_INVITATION_EXIST   133
#define IDS_AUTHPAGE_HEADER             134
#define IDD_EXISTING_INVITATIONS        135
#define IDS_AUTHPAGE_SUBTITLE           135
#define IDS_SAVE_INVITE_DLG_CAPTION     136
#define IDS_INVITE_FILE_EXTENSION       137
#define IDD_NEW_SESSION                 138
#define IDS_EXISTINGPAGE_HEADER         138
#define IDS_ERR_INVALID_INVITATION_FILEPATH 139
#define IDS_ERR_EMPTY_PASSWORD          140
#define IDR_TRAY_POPUP                  141
#define IDS_EXISTINGPAGE_SUBTITLE       141
#define IDS_ERR_PASSWORD_NO_MATCH       142
#define IDR_MAINFRAME                   143
#define IDS_INVITESAVEPAGE_HEADER       143
#define IDD_PROGRESS_DIALOG             144
#define IDS_INVITESAVEPAGE_SUBTITLE     144
#define IDC_PROGRESS                    145
#define IDS_MAIL_SEND_SUCCESS           145
#define IDS_SESSIONPAGE_HEADER          146
#define IDS_MAIL_SEND_FAILED            147
#define IDS_MAIL_SEND_POST_DATA         148
#define IDS_MAIL_DEFAULT_MESSAGE        149
#define IDS_PASSWORD_LEN_LESS           150
#define IDB_BITMAP1                     153
#define IDD_CONTACT_SUPPORT             154
#define IDR_ONLINE_PEER_CONTEXTMENU     155
#define IDC_ONLINE_PEERS                1000
#define IDC_JOIN_NICKNAME               1001
#define IDC_COMBO1                      1002
#define IDC_EXISTING_INVITATION_LIST    1002
#define IDC_BROWSE                      1003
#define IDC_JOIN_PASSWORD               1004
#define IDC_CREATE_NICKNAME             1006
#define IDC_SESSION_LIST                1007
#define IDC_FILEPATH                    1008
#define IDC_PASSWORD                    1009
#define IDC_CONFIRM_PASSWORD            1010
#define IDC_EXPIRY_DATE_LISTS           1011
#define IDC_DELETE_INVITATION           1012
#define IDC_SESSION_NAME                1013
#define IDC_PORT_INFORMATION            1014
#define IDC_ADVANCED_BUTTON             1015
#define IDC_ADD_PROCESS                 1018
#define IDC_PROCESS_LIST                1019
#define ID_ADD                          1020
#define IDC_ADD_NEW_SESSION             1021
#define IDC_CLOSE                       1022
#define IDC_STATUS_UPDATE_EDIT          1023
#define IDC_EXPIRY_TIME                 1023
#define IDC_ADD                         1024
#define IDB_CLOSE                       1024
#define IDC_JOIN                        1025
#define IDC_EXISTING                    1026
#define IDC_SLIDER1                     1027
#define IDC_FROM_E_MAIL                 1028
#define IDC_SUBJECT_EMAIL               1029
#define IDC_MESSAGE_EMAIL               1030
#define IDC_SEND                        1031
#define IDC_USERNAME                    1032
#define IDM_CLOSE                       32771
#define IDM_INVITE_PARTNER              32772
#define IDM_PARTNER                     32773
#define IDM_JOIN_PARTNER                32774
#define IDM_EXIT                        32775
#define ID_HELP32776                    32776
#define ID_FILE_EXISTINGNETWORK         32777
#define IDM_EXISTING_INVITATIONS        32778
#define ID_SHOWLANOIPRO                 32779
#define ID_EXIT                         32780
#define ID_SHOWLANOIPRO32781            32781
#define ID_POPUP_SHOWLAN                32782
#define ID_POPUP_EXIT                   32783
#define ID_HELP_CONTACTSUPPORT          32784
#define ID_HELP_ABOUT                   32785
#define ID_Menu                         32786
#define IDM_REFRESH                     32787
#define ID_POPUP_CLOSESESSION           32788
#define ID_CLOSESESSION                 32789

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32790
#define _APS_NEXT_CONTROL_VALUE         1033
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
