//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by cmnresource.rc
//
#define IDS_FAILED_TO_CREATE_FILE       10001
#define IDS_FAILED_OPEN_FILE            10002
#define IDS_WRONG_FILE_PASSWORD         10003
#define IDS_ERR_IPC_FAILED_TO_START     10004
#define IDS_ERR_SERVICE_CONNECT_FAILED  10005
#define IDS_ERR_IPC_READ_WRITE_ERROR    10006
#define IDS_ERR_FAILED_TO_GET_PUBLIC_KEY 10007
#define IDS_ERR_FAILED_TO_FILL_SUBJECT  10008
#define IDS_ERR_FAILED_TO_SET_KEY       10009
#define IDS_ERR_SIGN_FAILED             10010
#define IDS_ERR_CA_CERT_INFO_FAILED     10011
#define IDS_ERR_PFX_CONVERSION_FAILED   10012
#define IDS_ERR_IMPORT_PFX              10013
#define IDS_ERR_SSL_CERTIFICATE_VALIDATE_FAILED 10014
#define IDS_FAILED_GET_SUBJECT_NAME     10015
#define IDS_ERR_FAILED_TO_GET_BLOB      10016
#define IDS_FAILED_TO_ACQUIRE_CONTEXT   10017
#define IDS_VISTA_RA_GUIDE_HLP          10018
#define IDS_NETMEETING_SESSION_NAME     10019
#define IDS_RA_SESSION_NAME             10020
#define IDS_RA_INVITATION_FILE_FORMAT   10021
#define IDS_RA_CREATE_FAILED            10022
#define IDS_RA_XML_VISTA_FORMAT         10023
#define IDS_REMOTE_STREAM_SESSION_NAME  10024
#define IDS_RDP_SESSION_NAME            10025

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
